version: "3"
services:
  nacos3:
    container_name: nacos3
    image: nacos/nacos-server:1.4.0
    volumes:
      - ./cluster-logs/nacos3:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    env_file:
      - ./env/nacos.env
    restart: always
    networks:
      - nacos_net
networks:
  nacos_net:
    external: true