version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.4.0
    container_name: nacos-standalone-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./logs/standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - nacos-mysql
    restart: on-failure
    networks:
      - nacos_net

  nacos-mysql:
    container_name: nacos-mysql
    hostname: nacos-mysql
    image: nacos/nacos-mysql:5.7
    env_file:
      - ./env/mysql.env
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    networks:
      - nacos_net

networks:
  nacos_net:
    external: true